name: Deploy Pages

on:
    workflow_call:
        inputs:
            ref:
                required: false
                default: ""
                type: string

permissions:
    contents: read
    pages: write
    id-token: write

concurrency:
    group: pages
    cancel-in-progress: true

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            JEKYLL_ENV: production
            PAGES_REPO_NWO: thechelsuk/uk.thechels.feeds

        steps:
            - name: Checkout requested ref
              if: inputs.ref != ''
              uses: actions/checkout@v6
              with:
                  ref: ${{ inputs.ref }}

            - name: Checkout current ref
              if: inputs.ref == ''
              uses: actions/checkout@v6

            - name: Setup Pages
              id: pages
              uses: actions/configure-pages@v6

            - name: Setup Ruby
              uses: ruby/setup-ruby@v1
              with:
                  ruby-version: 3.3.11
                  bundler-cache: true

            - name: Build site
              run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"

            - name: Upload artifact
              uses: actions/upload-pages-artifact@v4
              with:
                  path: _site

    deploy:
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        needs: build

        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
